name: Trigger Pushover Notification

on:
  repository_dispatch:
    types: [heart-button]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message via Pushover API
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER }}" \
            --form-string "message=🌸 Front Updated! 💓" \
            https://pushover.net
